P: {(*x),1_x} ({(`$;{"J"$1_-1_x})@'" "\:x};{`$", "\:x}) @' {$[1=#x;x,,"";x]} {" -> "\:x} @
P (0:`:day7.input) 0
P (0:`:day7.input) 1
I:+`n`w`c!+P'0:`:day7.input
*(I`n)@&~(I`n)in?,/I`c /p1
K:1!I
W:{$[^x;0;(+/w'(K x)`c)+(K x)`w]}
J:![I;();0b;(,`t)!,((';@);W;`n)]
J[`p]:(J`n)@*:'&:'(J`n) in/:\: (J`c)
q)select from (update cw:W @/:/: c from J) where 1 < count each distinct each cw
q)select from (update cw:W @/:/: c from J) where n=`vrgxe