max_width = 120
ideal_width = 80
tab_spaces = 4
fn_call_width = 40
struct_lit_width = 20
newline_style = "Unix"
fn_brace_style = "AlwaysNextLine"
item_brace_style = "AlwaysNextLine"
else_if_brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
fn_return_indent = "WithArgs"
fn_args_paren_newline = true
struct_trailing_comma = "Vertical"
wrap_comments = true
report_todo = "Always"
report_fixme = "Always"
reorder_imports = true
match_block_trailing_comma = true
wrap_match_arms = false # this has been causing problems